from engine.rules.aws.autoscaling.controls import (
    build_autoscaling_elb_health_checks_finding,
    build_autoscaling_imdsv2_finding,
    build_autoscaling_launch_template_finding,
    build_autoscaling_multiple_az_finding,
    build_autoscaling_multiple_instance_types_finding,
    build_autoscaling_public_ip_finding,
    build_autoscaling_tags_finding,
    check_autoscaling_elb_health_checks,
    check_autoscaling_imdsv2,
    check_autoscaling_launch_template,
    check_autoscaling_multiple_az,
    check_autoscaling_multiple_instance_types,
    check_autoscaling_public_ip,
    check_autoscaling_tags,
)
from engine.rules.model import RuleDefinition
from engine.rules.registry.base import RuleRegistry


AUTOSCALING_RULES = RuleRegistry(
    [
        RuleDefinition(
            rule_id="CS-AWS-AUTOSCALING-001",
            name="autoscaling_elb_health_checks",
            data_source="autoscaling_groups",
            collection_mode="multiple",
            check_arguments=[
                "group_name",
                "group_arn",
                "has_load_balancer",
                "health_check_type",
            ],
            check=check_autoscaling_elb_health_checks,
            build_finding=(
                build_autoscaling_elb_health_checks_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-AUTOSCALING-002",
            name="autoscaling_multiple_availability_zones",
            data_source="autoscaling_groups",
            collection_mode="multiple",
            check_arguments=[
                "group_name",
                "group_arn",
                "availability_zone_count",
            ],
            check=check_autoscaling_multiple_az,
            build_finding=(
                build_autoscaling_multiple_az_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-AUTOSCALING-003",
            name="autoscaling_imdsv2",
            data_source="autoscaling_groups",
            collection_mode="multiple",
            check_arguments=[
                "group_name",
                "group_arn",
                "launch_configuration_name",
                "launch_configuration_data_available",
                "metadata_http_tokens",
            ],
            check=check_autoscaling_imdsv2,
            build_finding=build_autoscaling_imdsv2_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-AUTOSCALING-005",
            name="autoscaling_public_ip",
            data_source="autoscaling_groups",
            collection_mode="multiple",
            check_arguments=[
                "group_name",
                "group_arn",
                "launch_configuration_name",
                "launch_configuration_data_available",
                "associate_public_ip_address",
            ],
            check=check_autoscaling_public_ip,
            build_finding=build_autoscaling_public_ip_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-AUTOSCALING-006",
            name="autoscaling_multiple_instance_types",
            data_source="autoscaling_groups",
            collection_mode="multiple",
            check_arguments=[
                "group_name",
                "group_arn",
                "instance_types",
                "instance_type_count",
                "instance_type_data_available",
                "uses_attribute_based_instance_types",
            ],
            check=check_autoscaling_multiple_instance_types,
            build_finding=(
                build_autoscaling_multiple_instance_types_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-AUTOSCALING-009",
            name="autoscaling_launch_template",
            data_source="autoscaling_groups",
            collection_mode="multiple",
            check_arguments=[
                "group_name",
                "group_arn",
                "has_launch_template",
            ],
            check=check_autoscaling_launch_template,
            build_finding=(
                build_autoscaling_launch_template_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-AUTOSCALING-010",
            name="autoscaling_tags",
            data_source="autoscaling_groups",
            collection_mode="multiple",
            check_arguments=[
                "group_name",
                "group_arn",
                "has_non_system_tags",
            ],
            check=check_autoscaling_tags,
            build_finding=build_autoscaling_tags_finding,
        ),
    ]
)
