from engine.rules.aws.elb.protection import (
    build_elb_desync_mitigation_finding,
    build_elb_deletion_protection_finding,
    build_elb_health_check_protocol_finding,
    build_elb_http_to_https_finding,
    build_elb_invalid_headers_finding,
    build_elb_listener_protocol_finding,
    build_elb_logging_finding,
    build_elb_multi_az_finding,
    build_elb_target_transport_finding,
    check_elb_desync_mitigation,
    check_elb_deletion_protection,
    check_elb_health_check_protocol,
    check_elb_http_to_https,
    check_elb_invalid_headers,
    check_elb_listener_protocol,
    check_elb_logging,
    check_elb_multi_az,
    check_elb_target_transport,
)
from engine.rules.model import RuleDefinition
from engine.rules.registry.base import RuleRegistry


ELB_RULES = RuleRegistry(
    [
        RuleDefinition(
            rule_id="CS-AWS-ELB-001",
            name="elb_http_to_https",
            data_source="elb_load_balancers",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "resource_type",
                "listeners",
            ],
            check=check_elb_http_to_https,
            build_finding=build_elb_http_to_https_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-ELB-002",
            name="elb_access_logging",
            data_source="elb_load_balancers",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "resource_type",
                "access_logs_enabled",
            ],
            check=check_elb_logging,
            build_finding=build_elb_logging_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-ELB-003",
            name="elb_deletion_protection",
            data_source="elb_load_balancers",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "resource_type",
                "deletion_protection",
            ],
            check=check_elb_deletion_protection,
            build_finding=build_elb_deletion_protection_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-ELB-004",
            name="alb_invalid_http_headers",
            data_source="elb_load_balancers",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "resource_type",
                "drop_invalid_headers",
            ],
            check=check_elb_invalid_headers,
            build_finding=build_elb_invalid_headers_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-ELB-005",
            name="alb_desync_mitigation",
            data_source="elb_load_balancers",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "resource_type",
                "desync_mitigation_mode",
            ],
            check=check_elb_desync_mitigation,
            build_finding=build_elb_desync_mitigation_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-ELB-006",
            name="elb_multi_availability_zone",
            data_source="elb_load_balancers",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "resource_type",
                "availability_zones",
            ],
            check=check_elb_multi_az,
            build_finding=build_elb_multi_az_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-ELB-007",
            name="elb_listener_encryption",
            data_source="elb_load_balancers",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "resource_type",
                "listeners",
            ],
            check=check_elb_listener_protocol,
            build_finding=build_elb_listener_protocol_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-ELB-008",
            name="elb_health_check_encryption",
            data_source="elb_load_balancers",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "resource_type",
                "target_groups",
            ],
            check=check_elb_health_check_protocol,
            build_finding=(
                build_elb_health_check_protocol_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-ELB-009",
            name="elb_target_transport_encryption",
            data_source="elb_load_balancers",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "resource_type",
                "target_groups",
            ],
            check=check_elb_target_transport,
            build_finding=(
                build_elb_target_transport_finding
            ),
        ),
    ]
)
