from engine.rules.model import RuleDefinition
from engine.rules.registry.base import RuleRegistry

from engine.rules.aws.iam.access_key_age import (
    build_access_key_age_finding,
    check_access_key_age,
)
from engine.rules.aws.iam.access_key_never_used import (
    build_access_key_never_used_finding,
    check_access_key_never_used,
)
from engine.rules.aws.iam.inactive_access_key import (
    build_inactive_access_key_finding,
    check_inactive_access_key,
)
from engine.rules.aws.iam.multiple_active_access_keys import (
    build_multiple_active_access_keys_finding,
    check_multiple_active_access_keys,
)
from engine.rules.aws.iam.multiple_authentication_methods import (
    build_multiple_authentication_methods_finding,
    check_multiple_authentication_methods,
)
from engine.rules.aws.iam.no_active_authentication_credential import (
    build_no_active_authentication_credential_finding,
    check_no_active_authentication_credential,
)
from engine.rules.aws.iam.root_mfa import (
    build_root_mfa_finding,
    check_root_mfa,
)
from engine.rules.aws.iam.root_access_key import (
    build_root_access_key_finding,
    check_root_access_key,
)
from engine.rules.aws.iam.stale_user import (
    build_stale_iam_user_finding,
    check_stale_iam_user,
)
from engine.rules.aws.iam.user_attached_policy import (
    build_user_attached_policy_finding,
    check_user_attached_policy,
)
from engine.rules.aws.iam.user_mfa import (
    build_user_mfa_finding,
    check_user_mfa,
)
from engine.rules.aws.iam.password_policy import (
    build_password_policy_finding,
    check_password_policy_minimum_length,
)
from engine.rules.aws.iam.password_policy_symbols import (
    check_password_policy_symbols,
    build_password_policy_symbols_finding,
)
from engine.rules.aws.iam.password_policy_numbers import (
    check_password_policy_numbers,
    build_password_policy_numbers_finding,
)
from engine.rules.aws.iam.password_policy_uppercase import (
    check_password_policy_uppercase,
    build_password_policy_uppercase_finding,
)
from engine.rules.aws.iam.password_policy_lowercase import (
    check_password_policy_lowercase,
    build_password_policy_lowercase_finding,
)
from engine.rules.aws.iam.password_reuse import (
    check_password_reuse,
    build_password_reuse_finding,
)
from engine.rules.aws.iam.unused_console_password import (
    check_unused_console_password,
    build_unused_console_password_finding,
)
from engine.rules.aws.iam.broad_user_policy import (
    check_broad_user_policy,
    build_broad_user_policy_finding,
)
from engine.rules.aws.iam.broad_group_policy import (
    check_broad_group_policy,
    build_broad_group_policy_finding,
)
from engine.rules.aws.iam.broad_user_inline_policy import (
    check_broad_user_inline_policy,
    build_broad_user_inline_policy_finding,
)
from engine.rules.aws.iam.broad_group_inline_policy import (
    check_broad_group_inline_policy,
    build_broad_group_inline_policy_finding,
)
from engine.rules.aws.iam.broad_action_restricted_resource import (
    check_broad_action_restricted_resource,
    build_broad_action_restricted_resource_finding,
)
from engine.rules.aws.iam.sensitive_credential_action import (
    check_sensitive_credential_action,
    build_sensitive_credential_action_finding,
)
from engine.rules.aws.iam.administrative_policy import (
    check_administrative_user_policy,
    build_administrative_user_policy_finding,
    check_administrative_group_policy,
    build_administrative_group_policy_finding,
)
from engine.rules.aws.iam.privilege_management_action import (
    check_privilege_management_action,
    build_privilege_management_action_finding,
)
from engine.rules.aws.iam.passrole_wildcard_resource import (
    check_passrole_wildcard_resource,
    build_passrole_wildcard_resource_finding,
)
from engine.rules.aws.iam.service_wildcard_action import (
    check_service_wildcard_action,
    build_service_wildcard_action_finding,
)
from engine.rules.aws.iam.notaction_wildcard_resource import (
    check_notaction_wildcard_resource,
    build_notaction_wildcard_resource_finding,
)
from engine.rules.aws.iam.notresource_broad_action import (
    check_notresource_broad_action,
    build_notresource_broad_action_finding,
)
from engine.rules.aws.iam.privileged_user_without_boundary import (
    check_privileged_user_without_boundary,
    build_privileged_user_without_boundary_finding,
)
from engine.rules.aws.iam.wildcard_role_trust_principal import (
    check_wildcard_role_trust_principal,
    build_wildcard_role_trust_principal_finding,
)
from engine.rules.aws.iam.self_modifiable_policy import (
    check_self_modifiable_policy,
    build_self_modifiable_policy_finding,
)
from engine.rules.aws.iam.cross_account_trust_without_condition import (
    check_cross_account_trust_without_condition,
    build_cross_account_trust_without_condition_finding,
)
from engine.rules.aws.iam.access_analyzer_security_warning import (
    check_access_analyzer_security_warning,
    build_access_analyzer_security_warning_finding,
)


IAM_RULES = RuleRegistry(
    [
        RuleDefinition(
            rule_id="CS-AWS-IAM-001",
            name="root_mfa",
            data_source="root_mfa",
            collection_mode="single",
            check_arguments=[
                "root_mfa_enabled",
            ],
            check=check_root_mfa,
            build_finding=build_root_mfa_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-021",
            name="root_access_key",
            data_source="root_access_key",
            collection_mode="single",
            check_arguments=[
                "access_keys_present",
            ],
            check=check_root_access_key,
            build_finding=build_root_access_key_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-022",
            name="user_attached_policy",
            data_source="user_attached_policies",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "managed_policy_count",
                "managed_policy_names",
                "inline_policy_count",
                "inline_policy_names",
            ],
            check=check_user_attached_policy,
            build_finding=build_user_attached_policy_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-002",
            name="user_mfa",
            data_source="iam_users",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "mfa_devices",
            ],
            check=check_user_mfa,
            build_finding=build_user_mfa_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-003",
            name="access_key_age",
            data_source="iam_access_keys",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "access_key_id",
                "status",
                "created_at",
                "current_time",
            ],
            check=check_access_key_age,
            build_finding=build_access_key_age_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-004",
            name="inactive_access_key",
            data_source="iam_access_keys",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "access_key_id",
                "status",
                "created_at",
            ],
            check=check_inactive_access_key,
            build_finding=build_inactive_access_key_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-005",
            name="password_policy_minimum_length",
            data_source="password_policy",
            collection_mode="single",
            check_arguments=[
                "minimum_password_length",
            ],
            check=check_password_policy_minimum_length,
            build_finding=build_password_policy_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-006",
            name="password_policy_symbols",
            data_source="password_policy",
            collection_mode="single",
            check_arguments=[
                "require_symbols",
            ],
            check=check_password_policy_symbols,
            build_finding=build_password_policy_symbols_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-007",
            name="password_policy_numbers",
            data_source="password_policy",
            collection_mode="single",
            check_arguments=[
                "require_numbers",
            ],
            check=check_password_policy_numbers,
            build_finding=build_password_policy_numbers_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-008",
            name="password_policy_uppercase",
            data_source="password_policy",
            collection_mode="single",
            check_arguments=[
                "require_uppercase",
            ],
            check=check_password_policy_uppercase,
            build_finding=build_password_policy_uppercase_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-009",
            name="password_policy_lowercase",
            data_source="password_policy",
            collection_mode="single",
            check_arguments=[
                "require_lowercase",
            ],
            check=check_password_policy_lowercase,
            build_finding=build_password_policy_lowercase_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-010",
            name="password_reuse",
            data_source="password_policy",
            collection_mode="single",
            check_arguments=[
                "password_reuse_prevention",
            ],
            check=check_password_reuse,
            build_finding=build_password_reuse_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-011",
            name="unused_console_password",
            data_source="credential_report",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "password_enabled",
                "password_last_used",
                "current_time",
            ],
            check=check_unused_console_password,
            build_finding=build_unused_console_password_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-012",
            name="broad_user_policy",
            data_source="broad_user_policies",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_broad_user_policy,
            build_finding=build_broad_user_policy_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-013",
            name="broad_group_policy",
            data_source="broad_group_policies",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "group_name",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_broad_group_policy,
            build_finding=build_broad_group_policy_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-014",
            name="broad_user_inline_policy",
            data_source="broad_user_inline_policies",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "policy_name",
                "statement_index",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_broad_user_inline_policy,
            build_finding=build_broad_user_inline_policy_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-015",
            name="broad_group_inline_policy",
            data_source="broad_group_inline_policies",
            collection_mode="multiple",
            check_arguments=[
                "group_name",
                "policy_name",
                "statement_index",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_broad_group_inline_policy,
            build_finding=build_broad_group_inline_policy_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-016",
            name="broad_action_restricted_resource",
            data_source="broad_action_restricted_resources",
            collection_mode="multiple",
            check_arguments=[
                "permission_source",
                "resource_id",
                "principal_type",
                "principal_id",
                "username",
                "group_name",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "statement_index",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_broad_action_restricted_resource,
            build_finding=build_broad_action_restricted_resource_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-017",
            name="multiple_active_access_keys",
            data_source="multiple_active_access_keys",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "active_access_key_count",
                "active_access_key_ids",
            ],
            check=check_multiple_active_access_keys,
            build_finding=build_multiple_active_access_keys_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-018",
            name="multiple_authentication_methods",
            data_source="multiple_authentication_methods",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "password_enabled",
                "active_access_key_count",
                "active_access_key_ids",
            ],
            check=check_multiple_authentication_methods,
            build_finding=build_multiple_authentication_methods_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-019",
            name="access_key_never_used",
            data_source="access_key_last_used",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "access_key_id",
                "status",
                "last_used_at",
            ],
            check=check_access_key_never_used,
            build_finding=build_access_key_never_used_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-020",
            name="no_active_authentication_credential",
            data_source="no_active_authentication_credentials",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "password_enabled",
                "active_access_key_count",
                "active_access_key_ids",
            ],
            check=check_no_active_authentication_credential,
            build_finding=build_no_active_authentication_credential_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-023",
            name="stale_iam_user",
            data_source="stale_iam_users",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "last_activity_at",
                "last_activity_type",
                "last_activity_access_key_id",
                "current_time",
            ],
            check=check_stale_iam_user,
            build_finding=build_stale_iam_user_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-024",
            name="sensitive_credential_action",
            data_source="broad_action_restricted_resources",
            collection_mode="multiple",
            check_arguments=[
                "permission_source",
                "resource_id",
                "principal_type",
                "principal_id",
                "username",
                "group_name",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "statement_index",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_sensitive_credential_action,
            build_finding=build_sensitive_credential_action_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-025",
            name="administrative_user_policy",
            data_source="broad_user_policies",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_administrative_user_policy,
            build_finding=build_administrative_user_policy_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-026",
            name="administrative_group_policy",
            data_source="administrative_group_policies",
            collection_mode="multiple",
            check_arguments=[
                "group_name",
                "policy_name",
                "policy_arn",
            ],
            check=check_administrative_group_policy,
            build_finding=build_administrative_group_policy_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-027",
            name="privilege_management_action",
            data_source="broad_action_restricted_resources",
            collection_mode="multiple",
            check_arguments=[
                "permission_source",
                "resource_id",
                "principal_type",
                "principal_id",
                "username",
                "group_name",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "statement_index",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_privilege_management_action,
            build_finding=build_privilege_management_action_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-028",
            name="passrole_wildcard_resource",
            data_source="broad_action_restricted_resources",
            collection_mode="multiple",
            check_arguments=[
                "permission_source",
                "resource_id",
                "principal_type",
                "principal_id",
                "username",
                "group_name",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "statement_index",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_passrole_wildcard_resource,
            build_finding=build_passrole_wildcard_resource_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-029",
            name="service_wildcard_action",
            data_source="broad_action_restricted_resources",
            collection_mode="multiple",
            check_arguments=[
                "permission_source",
                "resource_id",
                "principal_type",
                "principal_id",
                "username",
                "group_name",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "statement_index",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_service_wildcard_action,
            build_finding=build_service_wildcard_action_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-030",
            name="notaction_wildcard_resource",
            data_source="broad_action_restricted_resources",
            collection_mode="multiple",
            check_arguments=[
                "permission_source",
                "resource_id",
                "principal_type",
                "principal_id",
                "username",
                "group_name",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "statement_index",
                "effect",
                "not_action",
                "resource",
                "condition",
            ],
            check=check_notaction_wildcard_resource,
            build_finding=build_notaction_wildcard_resource_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-031",
            name="notresource_broad_action",
            data_source="broad_action_restricted_resources",
            collection_mode="multiple",
            check_arguments=[
                "permission_source",
                "resource_id",
                "principal_type",
                "principal_id",
                "username",
                "group_name",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "statement_index",
                "effect",
                "action",
                "not_resource",
                "condition",
            ],
            check=check_notresource_broad_action,
            build_finding=build_notresource_broad_action_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-032",
            name="privileged_user_without_boundary",
            data_source="privileged_users_without_boundary",
            collection_mode="multiple",
            check_arguments=[
                "username",
                "permissions_boundary",
                "policy_name",
                "policy_arn",
                "action",
                "resource",
                "permission_source",
                "condition",
            ],
            check=check_privileged_user_without_boundary,
            build_finding=build_privileged_user_without_boundary_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-033",
            name="wildcard_role_trust_principal",
            data_source="wildcard_role_trust_principals",
            collection_mode="multiple",
            check_arguments=[
                "role_name",
                "role_arn",
                "statement_index",
                "effect",
                "principal",
                "action",
                "condition",
            ],
            check=check_wildcard_role_trust_principal,
            build_finding=build_wildcard_role_trust_principal_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-034",
            name="self_modifiable_policy",
            data_source="self_modifiable_policies",
            collection_mode="multiple",
            check_arguments=[
                "permission_source",
                "resource_id",
                "principal_type",
                "principal_id",
                "username",
                "group_name",
                "policy_name",
                "policy_arn",
                "policy_version_id",
                "statement_index",
                "effect",
                "action",
                "resource",
                "condition",
            ],
            check=check_self_modifiable_policy,
            build_finding=build_self_modifiable_policy_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-IAM-035",
            name="cross_account_trust_without_condition",
            data_source="cross_account_role_trusts",
            collection_mode="multiple",
            check_arguments=[
                "role_name",
                "role_arn",
                "statement_index",
                "effect",
                "principal",
                "action",
                "condition",
            ],
            check=check_cross_account_trust_without_condition,
            build_finding=(
                build_cross_account_trust_without_condition_finding
            ),
        ),

        RuleDefinition(
            rule_id="CS-AWS-IAM-036",
            name="access_analyzer_security_warning",
            data_source="access_analyzer_policy_validation",
            collection_mode="multiple",
            check_arguments=[
                "permission_source",
                "policy_name",
                "policy_arn",
                "principals",
                "finding_type",
                "issue_code",
                "finding_details",
                "learn_more_link",
                "locations",
            ],
            check=check_access_analyzer_security_warning,
            build_finding=(
                build_access_analyzer_security_warning_finding
            ),
        ),
    ]
)
