from engine.rules.aws.msk.protection import (
    build_msk_connector_encryption_finding,
    build_msk_connector_logging_finding,
    build_msk_enhanced_monitoring_finding,
    build_msk_in_cluster_encryption_finding,
    build_msk_public_access_finding,
    build_msk_unauthenticated_access_finding,
    check_msk_connector_encryption,
    check_msk_connector_logging,
    check_msk_enhanced_monitoring,
    check_msk_in_cluster_encryption,
    check_msk_public_access,
    check_msk_unauthenticated_access,
)
from engine.rules.model import RuleDefinition
from engine.rules.registry.base import RuleRegistry


MSK_RULES = RuleRegistry(
    [
        RuleDefinition(
            rule_id="CS-AWS-MSK-001",
            name="msk_in_cluster_encryption",
            data_source="msk_clusters",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "in_cluster_encryption",
            ],
            check=check_msk_in_cluster_encryption,
            build_finding=(
                build_msk_in_cluster_encryption_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-MSK-002",
            name="msk_enhanced_monitoring",
            data_source="msk_clusters",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "cluster_type",
                "enhanced_monitoring",
            ],
            check=check_msk_enhanced_monitoring,
            build_finding=(
                build_msk_enhanced_monitoring_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-MSK-003",
            name="msk_connector_encryption",
            data_source="msk_connectors",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "encryption_type",
            ],
            check=check_msk_connector_encryption,
            build_finding=(
                build_msk_connector_encryption_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-MSK-004",
            name="msk_public_access",
            data_source="msk_clusters",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "cluster_type",
                "public_access_type",
            ],
            check=check_msk_public_access,
            build_finding=build_msk_public_access_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-MSK-005",
            name="msk_connector_logging",
            data_source="msk_connectors",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "logging_enabled",
            ],
            check=check_msk_connector_logging,
            build_finding=(
                build_msk_connector_logging_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-MSK-006",
            name="msk_unauthenticated_access",
            data_source="msk_clusters",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "unauthenticated_access",
            ],
            check=check_msk_unauthenticated_access,
            build_finding=(
                build_msk_unauthenticated_access_finding
            ),
        ),
    ]
)
