from engine.rules.aws.neptune.protection import (
    build_neptune_audit_logging_finding,
    build_neptune_backup_retention_finding,
    build_neptune_deletion_protection_finding,
    build_neptune_encryption_finding,
    build_neptune_iam_authentication_finding,
    build_neptune_multi_az_finding,
    build_neptune_snapshot_encryption_finding,
    build_neptune_snapshot_public_finding,
    check_neptune_audit_logging,
    check_neptune_backup_retention,
    check_neptune_deletion_protection,
    check_neptune_encryption,
    check_neptune_iam_authentication,
    check_neptune_multi_az,
    check_neptune_snapshot_encryption,
    check_neptune_snapshot_public,
)
from engine.rules.model import RuleDefinition
from engine.rules.registry.base import RuleRegistry


NEPTUNE_RULES = RuleRegistry(
    [
        RuleDefinition(
            rule_id="CS-AWS-NEPTUNE-001",
            name="neptune_encryption",
            data_source="neptune_clusters",
            collection_mode="multiple",
            check_arguments=[
                "db_cluster_id",
                "storage_encrypted",
            ],
            check=check_neptune_encryption,
            build_finding=build_neptune_encryption_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-NEPTUNE-002",
            name="neptune_audit_logging",
            data_source="neptune_clusters",
            collection_mode="multiple",
            check_arguments=[
                "db_cluster_id",
                "enabled_cloudwatch_logs_exports",
            ],
            check=check_neptune_audit_logging,
            build_finding=build_neptune_audit_logging_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-NEPTUNE-003",
            name="neptune_public_snapshot",
            data_source="neptune_snapshots",
            collection_mode="multiple",
            check_arguments=[
                "db_cluster_snapshot_id",
                "is_public",
            ],
            check=check_neptune_snapshot_public,
            build_finding=build_neptune_snapshot_public_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-NEPTUNE-004",
            name="neptune_deletion_protection",
            data_source="neptune_clusters",
            collection_mode="multiple",
            check_arguments=[
                "db_cluster_id",
                "deletion_protection",
            ],
            check=check_neptune_deletion_protection,
            build_finding=build_neptune_deletion_protection_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-NEPTUNE-005",
            name="neptune_backup_retention",
            data_source="neptune_clusters",
            collection_mode="multiple",
            check_arguments=[
                "db_cluster_id",
                "backup_retention_period",
            ],
            check=check_neptune_backup_retention,
            build_finding=build_neptune_backup_retention_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-NEPTUNE-006",
            name="neptune_snapshot_encryption",
            data_source="neptune_snapshots",
            collection_mode="multiple",
            check_arguments=[
                "db_cluster_snapshot_id",
                "storage_encrypted",
            ],
            check=check_neptune_snapshot_encryption,
            build_finding=build_neptune_snapshot_encryption_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-NEPTUNE-007",
            name="neptune_iam_authentication",
            data_source="neptune_clusters",
            collection_mode="multiple",
            check_arguments=[
                "db_cluster_id",
                "iam_database_authentication_enabled",
            ],
            check=check_neptune_iam_authentication,
            build_finding=build_neptune_iam_authentication_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-NEPTUNE-009",
            name="neptune_multi_az",
            data_source="neptune_clusters",
            collection_mode="multiple",
            check_arguments=[
                "db_cluster_id",
                "availability_zone_count",
            ],
            check=check_neptune_multi_az,
            build_finding=build_neptune_multi_az_finding,
        ),
    ]
)
