from engine.rules.aws.network_firewall.protection import (
    build_deletion_protection_finding,
    build_default_fragment_action_finding,
    build_default_full_packet_action_finding,
    build_logging_finding,
    build_multi_az_finding,
    build_policy_rule_group_finding,
    build_stateless_rule_group_not_empty_finding,
    build_subnet_change_protection_finding,
    check_deletion_protection,
    check_default_fragment_action,
    check_default_full_packet_action,
    check_logging,
    check_multi_az,
    check_policy_rule_group,
    check_stateless_rule_group_not_empty,
    check_subnet_change_protection,
)
from engine.rules.model import RuleDefinition
from engine.rules.registry.base import RuleRegistry


NETWORK_FIREWALL_RULES = RuleRegistry(
    [
        RuleDefinition(
            rule_id="CS-AWS-NETWORKFIREWALL-001",
            name="network_firewall_multi_az",
            data_source="network_firewalls",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "availability_zone_count",
                "availability_zones",
            ],
            check=check_multi_az,
            build_finding=build_multi_az_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-NETWORKFIREWALL-002",
            name="network_firewall_logging",
            data_source="network_firewalls",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "logging_enabled",
                "log_destination_count",
            ],
            check=check_logging,
            build_finding=build_logging_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-NETWORKFIREWALL-003",
            name="network_firewall_policy_rule_group",
            data_source="network_firewall_policies",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "has_rule_group",
                "stateless_rule_group_count",
                "stateful_rule_group_count",
            ],
            check=check_policy_rule_group,
            build_finding=build_policy_rule_group_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-NETWORKFIREWALL-004",
            name="network_firewall_default_full_packet_action",
            data_source="network_firewall_policies",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "stateless_default_actions",
            ],
            check=check_default_full_packet_action,
            build_finding=(
                build_default_full_packet_action_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-NETWORKFIREWALL-005",
            name="network_firewall_default_fragment_action",
            data_source="network_firewall_policies",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "stateless_fragment_default_actions",
            ],
            check=check_default_fragment_action,
            build_finding=(
                build_default_fragment_action_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-NETWORKFIREWALL-006",
            name="network_firewall_stateless_rule_group_not_empty",
            data_source=(
                "network_firewall_stateless_rule_groups"
            ),
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "stateless_rule_count",
            ],
            check=check_stateless_rule_group_not_empty,
            build_finding=(
                build_stateless_rule_group_not_empty_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-NETWORKFIREWALL-009",
            name="network_firewall_deletion_protection",
            data_source="network_firewalls",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "delete_protection",
            ],
            check=check_deletion_protection,
            build_finding=(
                build_deletion_protection_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-NETWORKFIREWALL-010",
            name="network_firewall_subnet_change_protection",
            data_source="network_firewalls",
            collection_mode="multiple",
            check_arguments=[
                "resource_id",
                "subnet_change_protection",
            ],
            check=check_subnet_change_protection,
            build_finding=(
                build_subnet_change_protection_finding
            ),
        ),
    ]
)
