from engine.rules.model import RuleDefinition
from engine.rules.registry.base import RuleRegistry

from engine.rules.aws.redshift.protection import (
    build_redshift_allow_version_upgrade_finding,
    build_redshift_audit_logging_finding,
    build_redshift_backup_retention_finding,
    build_redshift_default_admin_finding,
    build_redshift_encryption_finding,
    build_redshift_enhanced_vpc_routing_finding,
    build_redshift_multi_az_finding,
    build_redshift_public_access_finding,
    build_redshift_require_ssl_finding,
    build_redshift_unrestricted_port_finding,
    check_redshift_allow_version_upgrade,
    check_redshift_audit_logging,
    check_redshift_backup_retention,
    check_redshift_default_admin,
    check_redshift_encryption,
    check_redshift_enhanced_vpc_routing,
    check_redshift_multi_az,
    check_redshift_public_access,
    check_redshift_require_ssl,
    check_redshift_unrestricted_port,
)


REDSHIFT_RULES = RuleRegistry(
    [
        RuleDefinition(
            rule_id="CS-AWS-REDSHIFT-001",
            name="redshift_public_access",
            data_source="redshift_clusters",
            collection_mode="multiple",
            check_arguments=[
                "cluster_identifier",
                "publicly_accessible",
            ],
            check=check_redshift_public_access,
            build_finding=build_redshift_public_access_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-REDSHIFT-002",
            name="redshift_require_ssl",
            data_source="redshift_clusters",
            collection_mode="multiple",
            check_arguments=[
                "cluster_identifier",
                "require_ssl",
            ],
            check=check_redshift_require_ssl,
            build_finding=build_redshift_require_ssl_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-REDSHIFT-003",
            name="redshift_backup_retention",
            data_source="redshift_clusters",
            collection_mode="multiple",
            check_arguments=[
                "cluster_identifier",
                "automated_snapshot_retention_period",
            ],
            check=check_redshift_backup_retention,
            build_finding=build_redshift_backup_retention_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-REDSHIFT-004",
            name="redshift_audit_logging",
            data_source="redshift_clusters",
            collection_mode="multiple",
            check_arguments=[
                "cluster_identifier",
                "audit_logging_enabled",
            ],
            check=check_redshift_audit_logging,
            build_finding=build_redshift_audit_logging_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-REDSHIFT-005",
            name="redshift_allow_version_upgrade",
            data_source="redshift_clusters",
            collection_mode="multiple",
            check_arguments=[
                "cluster_identifier",
                "allow_version_upgrade",
            ],
            check=check_redshift_allow_version_upgrade,
            build_finding=build_redshift_allow_version_upgrade_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-REDSHIFT-006",
            name="redshift_enhanced_vpc_routing",
            data_source="redshift_clusters",
            collection_mode="multiple",
            check_arguments=[
                "cluster_identifier",
                "enhanced_vpc_routing",
            ],
            check=check_redshift_enhanced_vpc_routing,
            build_finding=build_redshift_enhanced_vpc_routing_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-REDSHIFT-007",
            name="redshift_default_admin",
            data_source="redshift_clusters",
            collection_mode="multiple",
            check_arguments=[
                "cluster_identifier",
                "master_username",
            ],
            check=check_redshift_default_admin,
            build_finding=build_redshift_default_admin_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-REDSHIFT-008",
            name="redshift_encryption",
            data_source="redshift_clusters",
            collection_mode="multiple",
            check_arguments=[
                "cluster_identifier",
                "encrypted",
            ],
            check=check_redshift_encryption,
            build_finding=build_redshift_encryption_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-REDSHIFT-009",
            name="redshift_unrestricted_port",
            data_source="redshift_clusters",
            collection_mode="multiple",
            check_arguments=[
                "cluster_identifier",
                "cluster_port",
                "security_group_ingress",
            ],
            check=check_redshift_unrestricted_port,
            build_finding=build_redshift_unrestricted_port_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-REDSHIFT-010",
            name="redshift_multi_az",
            data_source="redshift_clusters",
            collection_mode="multiple",
            check_arguments=[
                "cluster_identifier",
                "multi_az",
            ],
            check=check_redshift_multi_az,
            build_finding=build_redshift_multi_az_finding,
        ),
    ]
)
