from engine.rules.aws.vpc.ec2_endpoint import (
    build_ec2_vpc_endpoint_finding,
    check_ec2_vpc_endpoint,
)
from engine.rules.aws.vpc.block_public_access import (
    build_vpc_block_public_access_finding,
    check_vpc_block_public_access,
)
from engine.rules.aws.vpc.default_security_group import (
    build_default_security_group_finding,
    check_default_security_group,
)
from engine.rules.aws.vpc.default_vpc import (
    build_default_vpc_finding,
    check_default_vpc,
)
from engine.rules.aws.vpc.flow_logs import (
    build_vpc_flow_logs_finding,
    check_vpc_flow_logs,
)
from engine.rules.aws.vpc.orphaned_internet_gateway import (
    build_orphaned_internet_gateway_finding,
    check_orphaned_internet_gateway,
)
from engine.rules.aws.vpc.nacl_remote_admin import (
    build_nacl_remote_admin_finding,
    check_nacl_remote_admin,
)
from engine.rules.aws.vpc.required_endpoints import (
    build_ecr_api_endpoint_finding,
    build_ecr_dkr_endpoint_finding,
    build_ssm_contacts_endpoint_finding,
    build_ssm_endpoint_finding,
    build_ssm_incidents_endpoint_finding,
    check_required_endpoint,
)
from engine.rules.aws.vpc.subnet_public_ip import (
    build_subnet_public_ip_finding,
    check_subnet_public_ip,
)
from engine.rules.aws.vpc.unused_network_acl import (
    build_unused_network_acl_finding,
    check_unused_network_acl,
)
from engine.rules.aws.vpc.unrestricted_network_acl import (
    build_unrestricted_network_acl_finding,
    check_unrestricted_network_acl,
)
from engine.rules.model import RuleDefinition
from engine.rules.registry.base import RuleRegistry


VPC_RULES = RuleRegistry(
    [
        RuleDefinition(
            rule_id="CS-AWS-VPC-001",
            name="default_vpc",
            data_source="vpcs",
            collection_mode="multiple",
            check_arguments=[
                "vpc_id",
                "cidr_block",
                "is_default",
            ],
            check=check_default_vpc,
            build_finding=build_default_vpc_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-002",
            name="orphaned_internet_gateway",
            data_source="internet_gateways",
            collection_mode="multiple",
            check_arguments=[
                "internet_gateway_id",
                "vpc_id",
                "state",
            ],
            check=check_orphaned_internet_gateway,
            build_finding=build_orphaned_internet_gateway_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-003",
            name="default_security_group",
            data_source="default_security_groups",
            collection_mode="multiple",
            check_arguments=[
                "group_id",
                "vpc_id",
                "group_name",
                "inbound_rule_count",
                "outbound_rule_count",
            ],
            check=check_default_security_group,
            build_finding=build_default_security_group_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-004",
            name="vpc_flow_logs",
            data_source="flow_log_coverage",
            collection_mode="multiple",
            check_arguments=[
                "vpc_id",
                "flow_log_count",
                "active_flow_log_count",
                "flow_logging_enabled",
            ],
            check=check_vpc_flow_logs,
            build_finding=build_vpc_flow_logs_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-006",
            name="ec2_vpc_endpoint",
            data_source="ec2_endpoint_coverage",
            collection_mode="multiple",
            check_arguments=[
                "vpc_id",
                "region",
                "ec2_endpoint_enabled",
            ],
            check=check_ec2_vpc_endpoint,
            build_finding=build_ec2_vpc_endpoint_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-007",
            name="vpc_block_public_access",
            data_source="vpc_block_public_access_options",
            collection_mode="single",
            check_arguments=[
                "region",
                "internet_gateway_block_mode",
                "state",
                "managed_by",
                "exclusions_allowed",
            ],
            check=check_vpc_block_public_access,
            build_finding=build_vpc_block_public_access_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-008",
            name="subnet_public_ip",
            data_source="subnet_public_ip_coverage",
            collection_mode="multiple",
            check_arguments=[
                "subnet_id",
                "vpc_id",
                "map_public_ip_on_launch",
            ],
            check=check_subnet_public_ip,
            build_finding=build_subnet_public_ip_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-009",
            name="unused_network_acl",
            data_source="unused_network_acl_coverage",
            collection_mode="multiple",
            check_arguments=[
                "network_acl_id",
                "vpc_id",
                "association_count",
                "is_default",
            ],
            check=check_unused_network_acl,
            build_finding=build_unused_network_acl_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-010",
            name="nacl_remote_admin",
            data_source="network_acls",
            collection_mode="multiple",
            check_arguments=[
                "network_acl_id",
                "vpc_id",
                "rule_number",
                "egress",
                "protocol",
                "cidr_block",
                "ipv6_cidr_block",
                "from_port",
                "to_port",
            ],
            check=check_nacl_remote_admin,
            build_finding=build_nacl_remote_admin_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-011",
            name="ecr_api_endpoint",
            data_source="ecr_api_endpoint_coverage",
            collection_mode="multiple",
            check_arguments=[
                "vpc_id",
                "region",
                "service_name",
                "endpoint_type",
                "endpoint_enabled",
            ],
            check=check_required_endpoint,
            build_finding=build_ecr_api_endpoint_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-012",
            name="ecr_dkr_endpoint",
            data_source="ecr_dkr_endpoint_coverage",
            collection_mode="multiple",
            check_arguments=[
                "vpc_id",
                "region",
                "service_name",
                "endpoint_type",
                "endpoint_enabled",
            ],
            check=check_required_endpoint,
            build_finding=build_ecr_dkr_endpoint_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-013",
            name="ssm_endpoint",
            data_source="ssm_endpoint_coverage",
            collection_mode="multiple",
            check_arguments=[
                "vpc_id",
                "region",
                "service_name",
                "endpoint_type",
                "endpoint_enabled",
            ],
            check=check_required_endpoint,
            build_finding=build_ssm_endpoint_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-014",
            name="ssm_contacts_endpoint",
            data_source="ssm_contacts_endpoint_coverage",
            collection_mode="multiple",
            check_arguments=[
                "vpc_id",
                "region",
                "service_name",
                "endpoint_type",
                "endpoint_enabled",
            ],
            check=check_required_endpoint,
            build_finding=build_ssm_contacts_endpoint_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-015",
            name="ssm_incidents_endpoint",
            data_source="ssm_incidents_endpoint_coverage",
            collection_mode="multiple",
            check_arguments=[
                "vpc_id",
                "region",
                "service_name",
                "endpoint_type",
                "endpoint_enabled",
            ],
            check=check_required_endpoint,
            build_finding=build_ssm_incidents_endpoint_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-VPC-005",
            name="unrestricted_network_acl",
            data_source="network_acls",
            collection_mode="multiple",
            check_arguments=[
                "network_acl_id",
                "vpc_id",
                "is_default",
                "rule_number",
                "egress",
                "rule_action",
                "protocol",
                "cidr_block",
                "ipv6_cidr_block",
            ],
            check=check_unrestricted_network_acl,
            build_finding=build_unrestricted_network_acl_finding,
        ),
    ]
)
