"""add risk fields to findings

Revision ID: 2a3a1147608e
Revises: a65fbd272642
Create Date: 2026-09-17 06:27:46.965593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3a1147608e'
down_revision: Union[str, Sequence[str], None] = 'a65fbd272642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('risk_score', sa.Float(), nullable=False))
    op.add_column('findings', sa.Column('risk_level', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_findings_risk_level'), 'findings', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_risk_level'), table_name='findings')
    op.drop_column('findings', 'risk_level')
    op.drop_column('findings', 'risk_score')
    # ### end Alembic commands ###
