from engine.rules.model import RuleDefinition
from engine.rules.registry.base import RuleRegistry

from engine.rules.aws.cloudtrail.logging import (
    build_cloudtrail_logging_finding,
    check_cloudtrail_logging,
)
from engine.rules.aws.cloudtrail.no_trail import (
    build_cloudtrail_no_trail_finding,
    check_cloudtrail_no_trail,
)
from engine.rules.aws.cloudtrail.log_file_validation import (
    build_cloudtrail_log_file_validation_finding,
    check_cloudtrail_log_file_validation,
)
from engine.rules.aws.cloudtrail.multi_region import (
    build_cloudtrail_multi_region_finding,
    check_cloudtrail_multi_region,
)
from engine.rules.aws.cloudtrail.global_service_events import (
    build_cloudtrail_global_service_events_finding,
    check_cloudtrail_global_service_events,
)
from engine.rules.aws.cloudtrail.encryption import (
    build_cloudtrail_encryption_finding,
    check_cloudtrail_encryption,
)
from engine.rules.aws.cloudtrail.management_events import (
    build_cloudtrail_management_events_finding,
    check_cloudtrail_management_events,
)
from engine.rules.aws.cloudtrail.cloudwatch_logs import (
    build_cloudtrail_cloudwatch_logs_finding,
    check_cloudtrail_cloudwatch_logs,
)
from engine.rules.aws.cloudtrail.event_data_store_encryption import (
    build_cloudtrail_event_data_store_encryption_finding,
    check_cloudtrail_event_data_store_encryption,
)
from engine.rules.aws.cloudtrail.event_data_store_termination_protection import (
    build_cloudtrail_event_data_store_termination_protection_finding,
    check_cloudtrail_event_data_store_termination_protection,
)
from engine.rules.aws.cloudtrail.event_data_store_retention import (
    build_cloudtrail_event_data_store_retention_finding,
    check_cloudtrail_event_data_store_retention,
)
from engine.rules.aws.cloudtrail.event_data_store_ingestion import (
    build_cloudtrail_event_data_store_ingestion_finding,
    check_cloudtrail_event_data_store_ingestion,
)
from engine.rules.aws.cloudtrail.event_data_store_management_events import (
    build_cloudtrail_event_data_store_management_events_finding,
    check_cloudtrail_event_data_store_management_events,
)
from engine.rules.aws.cloudtrail.event_data_store_multi_region import (
    build_cloudtrail_event_data_store_multi_region_finding,
    check_cloudtrail_event_data_store_multi_region,
)
from engine.rules.aws.cloudtrail.event_data_store_organization import (
    build_cloudtrail_event_data_store_organization_finding,
    check_cloudtrail_event_data_store_organization,
)
from engine.rules.aws.cloudtrail.tagging import (
    build_cloudtrail_tagging_finding,
    check_cloudtrail_tagging,
)
from engine.rules.aws.cloudtrail.destination_bucket_public_access import (
    build_cloudtrail_destination_bucket_public_access_finding,
    check_cloudtrail_destination_bucket_public_access,
)
from engine.rules.aws.cloudtrail.destination_bucket_logging import (
    build_cloudtrail_destination_bucket_logging_finding,
    check_cloudtrail_destination_bucket_logging,
)
from engine.rules.aws.cloudtrail.sns_topic_policy import (
    build_cloudtrail_sns_topic_policy_finding,
    check_cloudtrail_sns_topic_policy,
)
from engine.rules.aws.cloudtrail.destination_bucket_policy import (
    build_cloudtrail_destination_bucket_policy_finding,
    check_cloudtrail_destination_bucket_policy,
)


CLOUDTRAIL_RULES = RuleRegistry(
    [
        RuleDefinition(
            rule_id="CS-AWS-CT-001",
            name="cloudtrail_logging_enabled",
            data_source="cloudtrail_trails",
            collection_mode="multiple",
            check_arguments=[
                "trail_arn",
                "name",
                "is_logging",
            ],
            check=check_cloudtrail_logging,
            build_finding=build_cloudtrail_logging_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-002",
            name="cloudtrail_trail_configured",
            data_source="cloudtrail_account",
            collection_mode="single",
            check_arguments=[
                "trail_count",
            ],
            check=check_cloudtrail_no_trail,
            build_finding=build_cloudtrail_no_trail_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-003",
            name="cloudtrail_log_file_validation",
            data_source="cloudtrail_trails",
            collection_mode="multiple",
            check_arguments=[
                "trail_arn",
                "name",
                "enable_log_file_validation",
            ],
            check=check_cloudtrail_log_file_validation,
            build_finding=build_cloudtrail_log_file_validation_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-004",
            name="cloudtrail_multi_region",
            data_source="cloudtrail_trails",
            collection_mode="multiple",
            check_arguments=[
                "trail_arn",
                "name",
                "is_multi_region_trail",
            ],
            check=check_cloudtrail_multi_region,
            build_finding=build_cloudtrail_multi_region_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-005",
            name="cloudtrail_global_service_events",
            data_source="cloudtrail_trails",
            collection_mode="multiple",
            check_arguments=[
                "trail_arn",
                "name",
                "include_global_service_events",
            ],
            check=check_cloudtrail_global_service_events,
            build_finding=build_cloudtrail_global_service_events_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-006",
            name="cloudtrail_encryption",
            data_source="cloudtrail_trails",
            collection_mode="multiple",
            check_arguments=[
                "trail_arn",
                "name",
                "kms_key_id",
            ],
            check=check_cloudtrail_encryption,
            build_finding=build_cloudtrail_encryption_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-007",
            name="cloudtrail_management_events",
            data_source="cloudtrail_trails",
            collection_mode="multiple",
            check_arguments=[
                "trail_arn",
                "name",
                "includes_management_events",
            ],
            check=check_cloudtrail_management_events,
            build_finding=build_cloudtrail_management_events_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-008",
            name="cloudtrail_cloudwatch_logs",
            data_source="cloudtrail_trails",
            collection_mode="multiple",
            check_arguments=[
                "trail_arn",
                "name",
                "cloudwatch_logs_log_group_arn",
                "cloudwatch_logs_role_arn",
            ],
            check=check_cloudtrail_cloudwatch_logs,
            build_finding=build_cloudtrail_cloudwatch_logs_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-009",
            name="cloudtrail_tagging",
            data_source="cloudtrail_trails",
            collection_mode="multiple",
            check_arguments=[
                "trail_arn",
                "name",
                "tags",
            ],
            check=check_cloudtrail_tagging,
            build_finding=build_cloudtrail_tagging_finding,
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-010",
            name="cloudtrail_event_data_store_encryption",
            data_source="cloudtrail_event_data_stores",
            collection_mode="multiple",
            check_arguments=[
                "event_data_store_arn",
                "name",
                "kms_key_id",
            ],
            check=check_cloudtrail_event_data_store_encryption,
            build_finding=(
                build_cloudtrail_event_data_store_encryption_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-011",
            name="cloudtrail_event_data_store_termination_protection",
            data_source="cloudtrail_event_data_stores",
            collection_mode="multiple",
            check_arguments=[
                "event_data_store_arn",
                "name",
                "termination_protection_enabled",
            ],
            check=check_cloudtrail_event_data_store_termination_protection,
            build_finding=(
                build_cloudtrail_event_data_store_termination_protection_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-012",
            name="cloudtrail_event_data_store_retention",
            data_source="cloudtrail_event_data_stores",
            collection_mode="multiple",
            check_arguments=[
                "event_data_store_arn",
                "name",
                "retention_period",
            ],
            check=check_cloudtrail_event_data_store_retention,
            build_finding=(
                build_cloudtrail_event_data_store_retention_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-013",
            name="cloudtrail_event_data_store_ingestion",
            data_source="cloudtrail_event_data_stores",
            collection_mode="multiple",
            check_arguments=[
                "event_data_store_arn",
                "name",
                "status",
            ],
            check=check_cloudtrail_event_data_store_ingestion,
            build_finding=(
                build_cloudtrail_event_data_store_ingestion_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-014",
            name="cloudtrail_event_data_store_management_events",
            data_source="cloudtrail_event_data_stores",
            collection_mode="multiple",
            check_arguments=[
                "event_data_store_arn",
                "name",
                "management_events_enabled",
            ],
            check=check_cloudtrail_event_data_store_management_events,
            build_finding=(
                build_cloudtrail_event_data_store_management_events_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-015",
            name="cloudtrail_event_data_store_multi_region",
            data_source="cloudtrail_event_data_stores",
            collection_mode="multiple",
            check_arguments=[
                "event_data_store_arn",
                "name",
                "multi_region_enabled",
            ],
            check=check_cloudtrail_event_data_store_multi_region,
            build_finding=(
                build_cloudtrail_event_data_store_multi_region_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-016",
            name="cloudtrail_event_data_store_organization",
            data_source="cloudtrail_event_data_stores",
            collection_mode="multiple",
            check_arguments=[
                "event_data_store_arn",
                "name",
                "organization_enabled",
            ],
            check=check_cloudtrail_event_data_store_organization,
            build_finding=(
                build_cloudtrail_event_data_store_organization_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-017",
            name="cloudtrail_destination_bucket_public_access",
            data_source="cloudtrail_destination_bucket_security",
            collection_mode="multiple",
            check_arguments=[
                "bucket_name",
                "public_access_block",
            ],
            check=check_cloudtrail_destination_bucket_public_access,
            build_finding=(
                build_cloudtrail_destination_bucket_public_access_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-018",
            name="cloudtrail_destination_bucket_logging",
            data_source="cloudtrail_destination_bucket_security",
            collection_mode="multiple",
            check_arguments=[
                "bucket_name",
                "logging_configuration",
            ],
            check=check_cloudtrail_destination_bucket_logging,
            build_finding=(
                build_cloudtrail_destination_bucket_logging_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-019",
            name="cloudtrail_sns_topic_policy_source_arn",
            data_source="cloudtrail_sns_topic_security",
            collection_mode="multiple",
            check_arguments=[
                "topic_arn",
                "trail_arns",
                "policy",
            ],
            check=check_cloudtrail_sns_topic_policy,
            build_finding=(
                build_cloudtrail_sns_topic_policy_finding
            ),
        ),
        RuleDefinition(
            rule_id="CS-AWS-CT-020",
            name="cloudtrail_destination_bucket_policy_source_arn",
            data_source="cloudtrail_destination_bucket_policy",
            collection_mode="multiple",
            check_arguments=[
                "bucket_name",
                "trail_arns",
                "bucket_policy",
            ],
            check=check_cloudtrail_destination_bucket_policy,
            build_finding=(
                build_cloudtrail_destination_bucket_policy_finding
            ),
        ),
    ]
)
